### ISSUE TITLE
Add zulu-8 tasks to java role as an alternative to openjdk-8

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/ala-install#267]
Some servers are (hopefully temporarily) stuck on Ubuntu-14.04 due to lack of human resources to migrate them. This has stranded our use of the system package `openjdk-8` in terms of security updates on these servers.

RedHat are the leads for OpenJDK-8 and OpenJDK-11 since Oracle dropped public support for it, however, they only provide `.rpm` packaging. 

Azul however, are still supporting packaging for OpenJDK-8 as `.deb` packages (named Zulu), so we should move to using that for Ubuntu-14.04. The basic idea is the following, which will need to be implanted into the java role.

```
- name: Add PPA key for Azul Apt repository
  apt_key:
    keyserver: "hkp://pool.sks-keyservers.net:80"
    id: "B1998361219BD9C9"
  when:
    - use_zulu8 is defined and use_zulu8
    - ansible_os_family == "Debian" and ansible_distribution_version == "14.04"

- name: Add Azul Apt repository for openjdk-8
  apt_repository:
    repo: "deb http://repos.azulsystems.com/ubuntu stable main"
    filename: "azul-openjdk-ppa"
    state: present
  when:
    - use_zulu8 is defined and use_zulu8
    - ansible_os_family == "Debian" and ansible_distribution_version == "14.04"

- name: install zulu-8 (Debian)
  apt: pkg=zulu-8 state=latest
  become: yes
  when:
    - use_zulu8 is defined and use_zulu8
    - ansible_os_family == "Debian" and ansible_distribution_version == "14.04"

- name: set java defaults for zulu-8
  set_fact:
    java_home: "/usr/lib/jvm/zulu-8-amd64/jre"
  when:
    - use_zulu8 is defined and use_zulu8
    - ansible_os_family == "Debian" and ansible_distribution_version == "14.04"

- name: Set JAVA_HOME  (Debian)
  lineinfile:
    dest="/etc/default/{{ tomcat }}"
    regexp="^JAVA_HOME"
    line="JAVA_HOME={{ java_home }}"
  become: yes
  when: 
    - use_zulu8 is defined and use_zulu8
    - ansible_os_family == "Debian" and ansible_distribution_version == "14.04"
```
