### ISSUE TITLE
geoserver re-run fails trying to change they previously changed password

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/ala-install#556]
This geoserver task works well initially:

```
- name: change root password
  uri:
    url: "{{ geoserver_url }}/rest/security/masterpw"
    method: "PUT"
    user: 'admin'
    password: 'geoserver'
    force_basic_auth: yes
    body: '{ "oldMasterPassword": "geoserver", "newMasterPassword": "{{ geoserver_password }}" }'
    status_code: 200
    body_format: json
  when: geoserver_password != "geoserver"
  tags:
    - password
    - geoserver
```

But repeating the install of `spatial` fails because `oldMasterPassword` is not `geoserver` as we changed it in the first run. 

As a result geoserver does not start and the spatial playbook does not ends correctly.

Workaround, skip `password` tag.

I'll send a PR with: 
```
  ignore_errors: yes
```
